version: '3.3'
volumes:
  data:
services:
  postgres:
    image: postgres:11.1-alpine
    container_name: GymPoint
    working_dir: /application
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gympoint
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
